name: hackoverflow_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  air_quality: ^4.0.0
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.1
  awesome_bottom_bar: ^1.0.0
  skeletonizer: ^1.1.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.6.0
  google_gemini: ^0.1.2
  google_generative_ai: ^0.2.2
  intl: ^0.19.0
  
  firebase_ml_model_downloader: ^0.2.4+17
  google_ml_vision: ^0.0.8
  tflite_flutter: ^0.10.4
  image_picker: ^1.0.7
  camera: ^0.10.5+9
  google_fonts: ^6.2.1
  flutter_image_compress: ^2.2.0
  image: ^4.1.7
  flutter_launcher_icons: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0



flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icons/icon.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true
  


  fonts:
    - family: man-r
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf

    - family: man-l
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf

    - family: man-b
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf

    - family: man-sb
      fonts:
        - asset: assets/fonts/Manrope-SemiBold.ttf


  assets:
    - assets/fonts/
    - icons/
    - icons/location.png
    - icons/home.png
    - icons/hamburger.png
    - icons/lady.jpg
    - icons/icon.png
    - assets/background/
    - icons/doctor1.png
    - icons/medicine1.png
